#!/usr/bin/env bash
# Regenerate the FULL Bluetooth vendor lookup tables from upstream sources.
# Dev-time only (needs network); the committed TSVs are a working seed so the
# crate builds/tests offline. Overwrites data/ieee_oui.tsv and
# data/bt_company_ids.tsv in place.
set -euo pipefail
cd "$(dirname "$0")/../crates/fluxfang-core/data"

echo "Fetching IEEE OUI registry..."
# IEEE oui.csv columns: Registry,Assignment,Organization Name,Organization Address
curl -fsSL https://standards-oui.ieee.org/oui/oui.csv \
  | tail -n +2 \
  | awk -F',' 'NF>=3 {
        gsub(/"/,"",$2); gsub(/"/,"",$3);
        oui=toupper(substr($2,1,2) ":" substr($2,3,2) ":" substr($2,5,2));
        print oui "\t" $3
    }' \
  | sort -u > ieee_oui.tsv.new
{ echo "# IEEE OUI assignments (generated by scripts/fetch-bt-vendor-data.sh)"; cat ieee_oui.tsv.new; } > ieee_oui.tsv
rm -f ieee_oui.tsv.new

echo "Fetching Bluetooth SIG company identifiers..."
# Bluetooth SIG publishes company_identifiers.yaml (value + name).
curl -fsSL https://bitbucket.org/bluetooth-SIG/public/raw/main/assigned_numbers/company_identifiers/company_identifiers.yaml \
  | awk '/- value:/{v=$3} /name:/{ $1=""; name=$0; sub(/^ */,"",name); gsub(/^"|"$/,"",name); if(v!=""){print v "\t" name; v=""} }' \
  | sort -n -u > bt_company_ids.tsv.new
{ echo "# Bluetooth SIG company identifiers (generated by scripts/fetch-bt-vendor-data.sh)"; cat bt_company_ids.tsv.new; } > bt_company_ids.tsv
rm -f bt_company_ids.tsv.new

echo "Done. Rebuild fluxfang-core to embed the updated tables."
